name: "jma"
version: "1.0.0"

profile: "jma"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros", "shared/macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  jma:
    +database: jma
    main:
      raw:
        +materialized: table
      mart:
        +materialized: view
